### PR TITLE
Fix the build with libwpe 1.14.0, improve FindWPE CMake module

### LINKED ISSUE #85: Build broken with libwpe 1.14.0
Excerpt from the build failure:

```
src/input/Libinput/LibinputServer.cpp: In member function ‘bool WPE::LibinputServer::handleKeyboardEvent(uint32_t, uint32_t, uint32_t)’:
src/input/Libinput/LibinputServer.cpp:86:17: error: ‘wpe_input_xkb_context_get_default’ was not declared in this scope
   86 |     auto* xkb = wpe_input_xkb_context_get_default();
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/input/Libinput/LibinputServer.cpp:119:18: error: ‘wpe_input_xkb_context_get_key_code’ was not declared in this scope
  119 |         keysym = wpe_input_xkb_context_get_key_code(xkb, code, !!state);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/input/Libinput/LibinputServer.cpp:126:22: error: ‘wpe_input_xkb_context_get_state’ was not declared in this scope
  126 |     auto* xkbState = wpe_input_xkb_context_get_state(xkb);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/input/Libinput/LibinputServer.cpp:127:52: error: ‘XKB_KEY_DOWN’ was not declared in this scope
  127 |     xkb_state_update_key(xkbState, code, !!state ? XKB_KEY_DOWN : XKB_KEY_UP);
      |                                                    ^~~~~~~~~~~~
src/input/Libinput/LibinputServer.cpp:127:67: error: ‘XKB_KEY_UP’ was not declared in this scope
  127 |     xkb_state_update_key(xkbState, code, !!state ? XKB_KEY_DOWN : XKB_KEY_UP);
      |                                                                   ^~~~~~~~~~
src/input/Libinput/LibinputServer.cpp:127:5: error: ‘xkb_state_update_key’ was not declared in this scope
  127 |     xkb_state_update_key(xkbState, code, !!state ? XKB_KEY_DOWN : XKB_KEY_UP);
      |     ^~~~~~~~~~~~~~~~~~~~
src/input/Libinput/LibinputServer.cpp:129:44: error: ‘XKB_STATE_MODS_DEPRESSED’ was not declared in this scope
  129 |         xkb_state_serialize_mods(xkbState, XKB_STATE_MODS_DEPRESSED),
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
src/input/Libinput/LibinputServer.cpp:129:9: error: ‘xkb_state_serialize_mods’ was not declared in this scope
  129 |         xkb_state_serialize_mods(xkbState, XKB_STATE_MODS_DEPRESSED),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
src/input/Libinput/LibinputServer.cpp:130:44: error: ‘XKB_STATE_MODS_LATCHED’ was not declared in this scope
  130 |         xkb_state_serialize_mods(xkbState, XKB_STATE_MODS_LATCHED),
      |                                            ^~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by aperezdc**
Add missing xkbcommon header inclusion, and fix+improve the `FindWPE.cmake` find-module to make it pick compilation flags which were added to `wpe-1.0.pc` and need to be used during the build of code that uses libwpe.

Fixes #85

### CODE REVIEW

File: cmake/FindWPE.cmake [hunk 1]
```diff
@@ -49,20 +50,44 @@ if(PC_WPE_FOUND)
...
-
 else()
     message(FATAL_ERROR "libwpe not found!")
 endif()
 
+if (WPE_INCLUDE_DIR AND NOT WPE_VERSION)
+    if (EXISTS "${WPE_INCLUDE_DIR}/wpe/version.h")
+        file(READ "${WPE_INCLUDE_DIR}/wpe/version.h" WPE_VERSION_CONTENT)
+
+        string(REGEX MATCH "#define +WPE_MAJOR_VERSION +\\(([0-9]+)\\)" _dummy "${WPE_VERSION_CONTENT}")
```
Comment (TingPing) [inline cmake/FindWPE.cmake:61]: I'm not a cmake person but this seems pretty fragile, do we not have a pkgconfig file to query?

Comment (aperezdc) [reply cmake/FindWPE.cmake:61]: Yes, the version will be picked from `wpe-1.0.pc` file, and this bit only used if the `.pc` file did not include a version (highly unlikely) or not present. The latter could happen, apparently that's a thing in Windows; and also the reason why we have this in the `FindWPE.cmake` file in the WebKit tree (from which I picked it).

On second thought, we could actually remove this part from the patch, as it is safe to assume that `WPEBackend-rdk` will always be built on Linux.

Comment (aperezdc) [reply cmake/FindWPE.cmake]: Done, updated!

**Review by TingPing — APPROVED** [review]
